name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    
    - name: Build Windows
      run: cargo build --release
    
    - name: Run Windows deployment script
      run: .\create_deployment.bat
      
    - name: Create Windows archive
      run: powershell Compress-Archive -Path lab-control-deployment -DestinationPath lab-control-system-windows.zip
    
    - name: Create Linux source package
      run: |
        mkdir lab-control-linux
        xcopy "src" "lab-control-linux\src\" /E /I
        copy "Cargo.toml" "lab-control-linux\"
        copy "Cargo.lock" "lab-control-linux\"
        xcopy "frontend" "lab-control-linux\frontend\" /E /I
        copy "README.md" "lab-control-linux\"
        copy "LINUX_README.md" "lab-control-linux\"
        copy "linux_setup.sh" "lab-control-linux\"
        copy "run_lab_control.sh" "lab-control-linux\"
        powershell Compress-Archive -Path lab-control-linux -DestinationPath lab-control-system-linux.zip
    
    - name: Upload both packages
      uses: softprops/action-gh-release@v1
      with:
        files: |
          lab-control-system-windows.zip
          lab-control-system-linux.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }